default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
mobile-small: styles/mobile-small.scss
instance-ticker-type-0: styles/instance-ticker-type-0.scss
instance-ticker-type-1: styles/instance-ticker-type-1.scss
instance-ticker-type-2: styles/instance-ticker-type-2.scss
instance-ticker-type-3: styles/instance-ticker-type-3.scss
instance-ticker-type-0-contrast: styles/instance-ticker-type-0-contrast.scss
instance-ticker-type-1-contrast: styles/instance-ticker-type-1-contrast.scss
instance-ticker-type-2-contrast: styles/instance-ticker-type-2-contrast.scss
instance-ticker-type-3-contrast: styles/instance-ticker-type-3-contrast.scss
instance-ticker-type-0-light: styles/instance-ticker-type-0-light.scss
instance-ticker-type-1-light: styles/instance-ticker-type-1-light.scss
instance-ticker-type-2-light: styles/instance-ticker-type-2-light.scss
instance-ticker-type-3-light: styles/instance-ticker-type-3-light.scss
missing: styles/missing.scss
missing-contrast: styles/missing-contrast.scss
missing-light: styles/missing-light.scss
mastodon-material: styles/mastodon-material.scss
mastodon-material-v1-dark: styles/mastodon-material-v1-dark.scss
mastodon-material-v1-black: styles/mastodon-material-v1-black.scss
mastodon-material-v2-light: styles/mastodon-material-v2-light.scss
mastodon-material-v2-dark: styles/mastodon-material-v2-dark.scss
mastodon-material-mastodon-light: styles/mastodon-material-mastodon-light.scss
mastodon-material-mastodon-dark: styles/mastodon-material-mastodon-dark.scss
mastodon-material-google-plus: styles/mastodon-material-google-plus.scss
